services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123123123
      MYSQL_DATABASE: prod
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      interval: 5s
      timeout: 5s
      retries: 10
      test: mysqladmin ping -h 127.0.0.1 -u root --password="123123123"

  api-golang:
    build:
      context: ./app-golang
    command: ./api
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  worker-golang:
    build:
      context: ./app-golang
    command: ./worker
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mysql_data:
